import { getContactDetails, getDictionary, getProcessSteps } from '@/lib/content';
import { consultationHref, localizedPath } from '@/lib/urls';
import { Arrow, Button, Container, Section, SectionHeading, TextLink } from '@/components/ui/primitives';
import type { Locale, Step, CollaborationModel } from '@/types/content';
import ui from '@/components/ui/ui.module.css';
import styles from './sections.module.css';

export function BrandDecoration({asset='hero',className=''}:{asset?:string;className?:string}) { return <div className={styles.decoration+' '+className} aria-hidden="true"><picture><source media="(max-width:767px)" srcSet={'/media/'+asset+'-mobile.webp'} /><img src={'/media/'+asset+'.webp'} width={960} height={640} loading="lazy" decoding="async" alt="" /></picture></div>; }
export function CatalogIntro({locale}:{locale:Locale}) { const c=getDictionary(locale); return <section className={styles.catalogIntro} data-hero data-catalog-intro><Container><div className={styles.catalogIntroGrid}><div><p className={ui.eyebrow}><span />{c.intro.eyebrow}</p><h1>{c.intro.title}</h1><p className={styles.introBody}>{c.intro.body}</p></div><div className={styles.introAside}><p className={styles.productMarker}>{c.brand.productLabel}</p><Button href={consultationHref(locale,{sourcePage:localizedPath(locale)})} location="catalog-intro">{c.ui.book}</Button><p className={styles.introCaption}>{c.intro.caption}</p></div></div></Container></section>; }
export function PageHero({eyebrow,title,body,children}:{eyebrow:string;title:string;body:string;children?:React.ReactNode}) { return <section className={styles.pageHero} data-hero><Container><p className={ui.eyebrow}><span />{eyebrow}</p><h1>{title}</h1><p className={styles.pageBody}>{body}</p>{children}</Container><div className={styles.pageArc} aria-hidden="true" /></section>; }
export function CollaborationModels({locale}:{locale:Locale}) { const c=getDictionary(locale); return <Section id="collaboration"><SectionHeading eyebrow={c.collaboration.eyebrow} title={c.collaboration.title} /><div className={styles.models}>{c.collaboration.items.map((item,i)=><article key={item.id} className={styles.model} data-reveal><span className={styles.modelNumber}>0{i+1}</span><h3>{item.title}</h3><p>{item.body}</p><p>{item.extras}</p><a href={consultationHref(locale,{model:item.id as CollaborationModel,sourcePage:localizedPath(locale)})} className={ui.textLink} data-model={item.id} data-cta="collaboration">{item.cta}<Arrow /></a>{i===1&&<><TextLink href={localizedPath(locale,'/ai-systems')}>{locale==='uk'?'Детальніше про AI-системи':'Explore AI systems'}</TextLink><BrandDecoration asset="explainer-videos" /></>}</article>)}</div></Section>; }
export function ProcessTimeline({steps,compact=false,headingLevel=3}:{steps:Step[];compact?:boolean;headingLevel?:2|3}) { const Heading=headingLevel===2?'h2':'h3'; return <ol className={styles.timeline+' '+(compact?styles.compactTimeline:'')}>{steps.map((step,i)=><li key={step.title} data-reveal><span className={styles.stepNumber}>{String(i+1).padStart(2,'0')}</span><div><Heading>{step.title}</Heading><p>{step.body}</p></div></li>)}</ol>; }
export function ProcessPreview({locale}:{locale:Locale}) { const c=getDictionary(locale).process; return <Section className={styles.process}><div className={styles.processHeading}><SectionHeading eyebrow={c.eyebrow} title={c.title} body={c.body}><TextLink href={localizedPath(locale,'/process')}>{c.link}</TextLink></SectionHeading><BrandDecoration asset="explainer-videos" /></div><ProcessTimeline steps={getProcessSteps(locale)} compact /></Section>; }
export function ConsultationCTA({locale,service,model,sourcePage,label}:{locale:Locale;service?:string;model?:CollaborationModel;sourcePage?:string;label?:string}) { const c=getDictionary(locale); return <section className={styles.ctaSection} id="consultation-idea"><Container><div className={styles.cta} data-reveal><BrandDecoration asset="hero" /><div className={styles.ctaArc} aria-hidden="true" /><p className={ui.eyebrow}><span />{c.cta.eyebrow}</p><h2>{c.cta.title}</h2><p className={styles.ctaBody}>{c.cta.body}</p><p className={styles.ctaBody}>{c.cta.discussion}</p><p className={styles.ctaBody}>{c.cta.note}</p><Button href={consultationHref(locale,{service,model,sourcePage})} location="consultation-idea" service={service}>{label??c.ui.bookLong}</Button></div></Container></section>; }
export function ConsultationValue({locale}:{locale:Locale}) { const c=getDictionary(locale).consultation; return <div className={styles.consultationValue} data-hero><p className={ui.eyebrow}><span />{c.eyebrow}</p><h1>{c.title}</h1><p className={styles.pageBody}>{c.body}</p><p className={styles.pageBody}>{c.discussion}</p><p className={styles.pageBody}>{c.after}</p><p className={styles.consultationNote}>{c.note}</p><div className={styles.miniArc} aria-hidden="true" /></div>; }
export function ContactLinks({locale}:{locale:Locale}) { const contact=getContactDetails(), c=getDictionary(locale).contact; return <div className={styles.contactLinks}><a href={contact.emailHref} data-contact="email"><span>{c.email}</span>{contact.email}<Arrow diagonal /></a><a href={contact.phoneHref} data-contact="phone"><span>{c.phone}</span><b className={styles.phone}>{contact.phone}</b><Arrow diagonal /></a>{contact.socialLinks.map(item=><a key={item.url} href={item.url} target="_blank" rel="noopener noreferrer" data-contact={item.label.toLowerCase()}><span>{c.socials}</span>{item.label}<Arrow diagonal /></a>)}</div>; }
export function HomeContact({locale}:{locale:Locale}) { const c=getDictionary(locale); return <Section id="contacts"><div className={styles.contactGrid}><SectionHeading eyebrow={c.contact.eyebrow} title={c.contact.title} body={c.contact.contactBody}><Button href={consultationHref(locale,{sourcePage:localizedPath(locale)})} location="home-contact">{c.ui.book}</Button></SectionHeading><ContactLinks locale={locale} /></div></Section>; }
