import type { Service } from '@/types/content';
import { defineService as buildService, type ServiceInput } from '../site/define-service';
const defineService = (input: ServiceInput) => buildService('en', input);

export const services: Service[] = [
  defineService({
    slug: 'ai-video-ads', professionalLabel: "AI Video Ads", title: "Advertising Videos",
    whatItIs: 'A complete production workflow for short advertising films. Generated scenes are directed, selected and finished through editing and post-production so they communicate one campaign idea.',
    shortPromise: "We create advertising videos for products, services and campaigns — from the initial idea and script to final editing.",
    overview: 'We shape your message into a directed visual story, then produce and finish the video assets your campaign needs. The work connects concept development, AI production, editing, sound and channel adaptations.',
    problems: ['A launch needs a distinctive visual world without a full location shoot.', 'Your media plan needs several creative routes, not one master film.', 'The campaign concept needs to work across short attention windows and multiple placements.'],
    bestFor: ['Brand and marketing teams preparing a launch', 'Agencies extending an approved campaign concept', 'Paid social teams that need directed creative variations'],
    deliverables: ['Creative routes and an approved storyboard', 'Finished master video with agreed sound treatment', 'Short cutdowns and opening-hook variations', 'Aspect-ratio adaptations and caption-ready versions'],
    formats: ['Paid social', 'Organic social', 'Landing pages', 'Retail screens'],
    clientInputs: ['Campaign brief and audience', 'Brand guidelines and approved claims', 'Product assets and accurate product details', 'Media placements, markets and legal restrictions'],
    relatedSlugs: ['performance-creatives', 'ai-ugc', 'video-localization'], accent: 'hot', cardSpan: 8,
    alt: 'Original cinematic composition of a luminous red sculptural ribbon inside an advertising frame.',
    starterAnswer: 'Share the campaign objective, key message, brand guidelines, product materials and intended placements. We’ll use these to define a first creative route.',
    specialQuestion: 'Can one concept become several campaign versions?', specialAnswer: 'Yes. Hook, length, aspect ratio and market variations can be planned in the scope so they stay connected to the approved direction.',
  }),
  defineService({
    slug: 'product-visuals', professionalLabel: "Product Visuals", title: "Product Photos & Videos",
    whatItIs: 'Art-directed still imagery that places a product in a considered setting. We combine supplied product references with generated environments and finishing, using the right technique for each accuracy requirement.',
    shortPromise: "We present your product in advertising scenes and locations without organising a full product shoot.",
    overview: 'We build controlled product worlds around your packaging, materials and brand language. Accurate references guide the production, with human review of product shape, labels and details before final delivery.',
    problems: ['A product range needs a coherent visual system across different scenes.', 'You need seasonal or campaign variations without organizing another set.', 'Product page and campaign imagery feel disconnected.'],
    bestFor: ['Consumer brands developing campaign imagery', 'Ecommerce teams refreshing product pages', 'Agencies exploring art direction for product launches'],
    deliverables: ['Approved visual direction and scene references', 'Finished product hero scenes', 'Background, composition or seasonal variations', 'Channel crops and web-ready exports'],
    formats: ['Product pages', 'Marketplace assets', 'Paid social', 'Landing pages', 'Presentations'],
    clientInputs: ['High-resolution product photographs or 3D assets', 'Packaging artwork and material details', 'Brand guidelines and visual references', 'Required crops, markets and product accuracy restrictions'],
    relatedSlugs: ['virtual-models', 'performance-creatives', 'brand-characters'], accent: 'acid', cardSpan: 4,
    alt: 'An unbranded metallic object on a reflective studio pedestal with a restrained green light.',
    starterAnswer: 'Provide clear product views, packaging artwork, dimensions where relevant and visual references. We’ll confirm what can be represented accurately.',
    specialQuestion: 'How do you handle product accuracy?', specialAnswer: 'We compare production output with supplied references and agree required corrections. If a detail cannot be preserved reliably, we discuss compositing or another production approach.',
  }),
  defineService({
    slug: 'virtual-models', professionalLabel: "Virtual Models", title: "Virtual Fashion Models",
    whatItIs: 'Synthetic casting developed for a specific editorial or product context. Each visual is reviewed for styling, representation and product fidelity; it does not document a real person wearing or endorsing a product.',
    shortPromise: "We create photos and videos with virtual models for clothing, accessories and fashion brands.",
    overview: 'We develop synthetic editorial casting and visual direction for product-led campaigns. Styling, scene design and consistency are reviewed together, with a clear distinction between illustrative production and a real person’s endorsement.',
    problems: ['A visual concept needs casting and styling options before production.', 'Different campaign images need a coherent editorial look.', 'You need synthetic model-led variations with explicit rights and disclosure decisions.'],
    bestFor: ['Fashion teams exploring campaign concepts', 'Beauty brands developing editorial visual worlds', 'Lifestyle brands with clear product references and usage requirements'],
    deliverables: ['Synthetic casting and styling direction', 'Approved editorial compositions', 'Posing, scene and crop variations', 'Final retouching and delivery in agreed formats'],
    formats: ['Paid social', 'Organic social', 'Product pages', 'Presentations'],
    clientInputs: ['Brand and casting direction', 'Accurate garment or product references', 'Required contexts, markets and formats', 'Rights, representation and disclosure requirements'],
    relatedSlugs: ['product-visuals', 'ai-video-ads', 'video-localization'], accent: 'hot', cardSpan: 4,
    alt: 'Clearly abstract sculptural editorial silhouette inside a pink-lit studio frame.',
    starterAnswer: 'Share brand references, product images, styling requirements and intended usage. We’ll agree synthetic casting and the accuracy checks before production.',
    specialQuestion: 'Can you reproduce a real person’s likeness?', specialAnswer: 'Only a separately agreed workflow with documented permission could use a real person’s likeness. Our default is original synthetic casting, with no implied real-person endorsement.',
    ethicalNote: 'No imitation of a real person without documented permission. Synthetic models are never presented as real employees, customers or influencers.',
  }),
  defineService({
    slug: 'ai-ugc', professionalLabel: "AI UGC", title: "UGC-Style Video Ads",
    whatItIs: 'Brand-authored advertising in familiar creator-style formats: direct product explanations, demonstrations and mobile narratives. The content is synthetic production, with claims grounded in approved product information.',
    shortPromise: "Review-, unboxing-, demonstration- and recommendation-style videos featuring an AI actor.",
    overview: 'We translate brand-approved messages into direct, mobile-first creative concepts. The focus is a useful demonstration or clear product narrative, with synthetic presentation handled honestly and no invented customer experience.',
    problems: ['Your social campaign needs different hooks and message structures.', 'Product information is too dense for a short mobile placement.', 'You need creator-style formats without inventing endorsements or personal stories.'],
    bestFor: ['Performance teams planning creative tests', 'Product brands with demonstrable, approved benefits', 'Agencies building mobile-first ad concepts'],
    deliverables: ['Hook and script options', 'Creator-style synthetic ad concepts', 'Product-focused demonstrations where feasible', 'Captioned edits and placement variations'],
    formats: ['Paid social', 'Organic social', 'Landing pages'],
    clientInputs: ['Audience and test hypotheses', 'Approved product facts and claims', 'Product assets and usage instructions', 'Platform, market and disclosure requirements'],
    relatedSlugs: ['performance-creatives', 'ai-video-ads', 'ai-spokesperson'], accent: 'acid', cardSpan: 4,
    alt: 'An abstract smartphone frame with a sculptural product and green editorial interface shapes.',
    starterAnswer: 'Bring the audience, product facts, approved claims and the messages you want to test. We’ll help choose a suitable script structure.',
    specialQuestion: 'Is this presented as a real customer testimonial?', specialAnswer: 'No. We do not fabricate customer experiences, testimonials or medical claims. Synthetic content is identified where required by the publishing context.',
    ethicalNote: 'No fabricated testimonials, medical claims or personal experiences. No creator impersonation. Confirm synthetic-content disclosures for the intended publishing context.',
  }),
  defineService({
    slug: 'ai-spokesperson', professionalLabel: "AI Spokesperson", title: "AI Presenters & Avatars",
    whatItIs: 'A scripted presentation format using an agreed synthetic or permissioned presenter and voice. The production system combines the speaker, supporting graphics and captions into a consistent message.',
    shortPromise: "A virtual presenter introduces a product, service or message using an approved script.",
    overview: 'We develop presenter-led communication around an approved script and visual system. Casting, voice, pacing and on-screen information are directed to make the message clear and repeatable across the agreed versions.',
    problems: ['Your team needs presenter-led updates on a repeatable schedule.', 'Product messages need a consistent voice and visual presentation.', 'Several markets need versions of the same approved message.'],
    bestFor: ['Product marketing teams with recurring communication needs', 'Businesses producing structured product education', 'Teams adapting approved messages across languages'],
    deliverables: ['Script development and presenter direction', 'Approved presenter-led master video', 'Captioned and graphic-supported versions', 'Language or message variations within agreed scope'],
    formats: ['Landing pages', 'Product pages', 'Internal communication', 'Paid social', 'Presentations'],
    clientInputs: ['Approved script or message brief', 'Brand assets and product information', 'Presenter and voice requirements', 'Likeness permissions, markets and disclosure restrictions'],
    relatedSlugs: ['explainer-videos', 'video-localization', 'ai-ugc'], accent: 'hot', cardSpan: 4,
    alt: 'Original abstract presenter silhouette framed by studio lighting and a simple audio waveform.',
    starterAnswer: 'Share the message, intended audience, brand references and rights requirements for any supplied face or voice assets.',
    specialQuestion: 'Can we use a specific face or voice?', specialAnswer: 'Any use of a real face or voice requires documented permission and an agreed scope of use. We do not use unauthorized cloning or public-figure likenesses.',
    ethicalNote: 'No unauthorized face or voice cloning and no public-figure likenesses. Rights and disclosure requirements are confirmed per project.',
  }),
  defineService({
    slug: 'video-localization', professionalLabel: "Video Localization", title: "Video Translation & Localization",
    whatItIs: 'A coordinated adaptation of an existing video for a different language or market. Localization can cover the script, voice, captions, on-screen graphics and technical delivery specifications.',
    shortPromise: "We adapt language, voice, graphics and delivery for different countries and audiences.",
    overview: 'We extend an approved video into a planned system of market versions. Translation, voice treatment, captions, graphics and final exports are coordinated, with language review responsibilities agreed before work starts.',
    problems: ['A strong master video is only usable in one market.', 'Subtitles, voice and on-screen graphics need to stay aligned.', 'Local teams need consistent versions without rebuilding the entire project.'],
    bestFor: ['Brands expanding an existing campaign into new markets', 'Marketing teams coordinating regional launches', 'Companies adapting product education or internal video'],
    deliverables: ['Language and version delivery matrix', 'Adapted scripts and timed subtitles', 'Localized voice and on-screen text versions', 'Market-ready exports with agreed language review'],
    formats: ['Paid social', 'Landing pages', 'Product pages', 'Internal communication', 'Retail screens'],
    clientInputs: ['Approved master video and editable assets where available', 'Target languages and market terminology', 'Existing translations and voice usage rights', 'Local reviewers and legal restrictions'],
    relatedSlugs: ['ai-spokesperson', 'ai-video-ads', 'explainer-videos'], accent: 'acid', cardSpan: 6,
    alt: 'Layered video frames, caption bars and a waveform in a green-lit modular composition.',
    starterAnswer: 'Provide the master video, available project files, target languages, terminology and a named review process for local accuracy.',
    specialQuestion: 'Who checks linguistic and cultural accuracy?', specialAnswer: 'We agree language review responsibilities in the scope. Specialist review or your local team’s approval is built into the workflow where required.',
  }),
  defineService({
    slug: 'explainer-videos', professionalLabel: "AI Explainers", title: "Explainer Videos",
    whatItIs: 'A focused visual explanation built around what the viewer needs to understand. We structure the narrative first, then use suitable imagery, diagrams, motion and narration to make each point clear.',
    shortPromise: "We turn a complex product, service or process into a clear visual story.",
    overview: 'We organize the information your audience needs, shape a focused narrative and build the visuals around it. Scripts, diagrams, motion and narration work together to explain a useful idea without overloading the viewer.',
    problems: ['Your product is difficult to explain in a short conversation.', 'A presentation needs a clear visual narrative.', 'Different audiences need different levels of product detail.'],
    bestFor: ['B2B product teams explaining a new offering', 'Service businesses clarifying a customer journey', 'Marketing and sales teams preparing launch or presentation content'],
    deliverables: ['Narrative structure and approved script', 'Storyboard and visual direction', 'Finished explainer with agreed narration and captions', 'Short versions or audience-specific adaptations'],
    formats: ['Landing pages', 'Product pages', 'Presentations', 'Internal communication', 'Organic social'],
    clientInputs: ['Product explanation and accurate feature information', 'Audience and communication objective', 'Brand guidelines and interface assets', 'Claims restrictions and subject-matter reviewers'],
    relatedSlugs: ['ai-spokesperson', 'video-localization', 'brand-characters'], accent: 'acid', cardSpan: 6,
    alt: 'A clean modular visual sequence connecting three dimensional blocks and interface fragments.',
    starterAnswer: 'Bring product information, your audience’s main questions and the one idea they should understand after watching.',
    specialQuestion: 'Can you help simplify a technical subject?', specialAnswer: 'Yes. We develop the narrative with your subject-matter reviewers and confirm factual accuracy before final production.',
  }),
  defineService({
    slug: 'brand-characters', professionalLabel: "Brand Characters", title: "Brand Characters & Mascots",
    whatItIs: 'An original visual character and a practical system for using it. Development includes personality, form, expression and contextual rules so the character can support recurring brand communication.',
    shortPromise: "We develop a recognisable character for advertising, social media and brand communication.",
    overview: 'We develop an original character around the brand’s role, personality and visual language. The work considers how the character behaves and how a team can use it consistently beyond a single image.',
    problems: ['Your brand needs a recognizable visual presence across touchpoints.', 'One-off character experiments are inconsistent.', 'Campaign teams need clear rules for expression, posing and reuse.'],
    bestFor: ['Brands developing a new visual communication device', 'Teams building recurring educational or campaign content', 'Agencies extending a brand identity system'],
    deliverables: ['Original character concept routes', 'Approved character design and expression studies', 'Pose or scene library within agreed scope', 'Practical usage guidance and channel-ready assets'],
    formats: ['Organic social', 'Paid social', 'Presentations', 'Landing pages', 'Product pages'],
    clientInputs: ['Brand values, audience and personality', 'Existing identity guidelines', 'Planned character contexts and formats', 'Originality, ownership and market restrictions'],
    relatedSlugs: ['explainer-videos', 'product-visuals', 'ai-video-ads'], accent: 'hot', cardSpan: 4,
    alt: 'An original rounded sculptural character with two inset eyes on a dark pink-lit plinth.',
    starterAnswer: 'Share the brand personality, audience and the role you want a character to play. References should describe qualities, not request copies of existing characters.',
    specialQuestion: 'How do you plan for consistent reuse?', specialAnswer: 'We agree a character system covering proportions, expressions and visual rules, then develop the pose or scene set needed for the first rollout.',
    ethicalNote: 'Characters are developed as original concepts, never copied from an existing franchise or presented as cleared intellectual property without an agreed review.',
  }),
  defineService({
    slug: 'performance-creatives', professionalLabel: "Performance Creatives", title: "Ad Creative Variations",
    whatItIs: 'An organized production batch where each variation has a reason to exist. Assets are mapped to agreed hypotheses, such as a different opening message or product framing, for your media team to evaluate.',
    shortPromise: "We create multiple ad variations to test different ideas, messages and visual approaches.",
    overview: 'We turn a testing brief into an organized creative batch: different hooks, messages, scenes and formats, all connected to a clear hypothesis. Delivery makes it easy for your media team to launch and identify each variation.',
    problems: ['Creative testing is limited by asset volume and disconnected file versions.', 'Your media team needs intentional variation instead of random changes.', 'Winning concepts need extensions across placements and audiences.'],
    bestFor: ['Paid media teams with a defined testing plan', 'Brands running recurring acquisition campaigns', 'Agencies coordinating creative production for media buyers'],
    deliverables: ['Creative testing and variation matrix', 'Agreed batch of static or video assets', 'Hook, message and format variations', 'Clearly named exports and a delivery index'],
    formats: ['Paid social', 'Landing pages', 'Marketplace assets'],
    clientInputs: ['Audience segments and test hypotheses', 'Approved offers and product claims', 'Existing creative learnings where available', 'Placement specifications and brand restrictions'],
    relatedSlugs: ['ai-video-ads', 'ai-ugc', 'product-visuals'], accent: 'hot', cardSpan: 8,
    alt: 'An organized matrix of original pink-lit abstract creative variants in multiple aspect ratios.',
    starterAnswer: 'Share your testing plan, audience segments, approved messages and placements. Existing creative learnings can help prioritize the first batch.',
    specialQuestion: 'Do you guarantee advertising results?', specialAnswer: 'No. We produce assets around explicit hypotheses. Campaign outcomes depend on the offer, audience, media execution and other factors outside creative production.',
  }),
];
